default:
  image: python:3.8
  before_script:
      - apt-get update
      - apt-get install -y python3-pip
      - pip install -r requirements.txt

stages:
  - test
  - docs

test:
  stage: test
  script:
    - cd Epi_SEIR
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: Epi_SEIR/report.xml

docs:
  - stage: docs
  - script:
    - cd Epi_SEIR/docs
    - make clean
    - make html
