pytest:
  stage: test
  script:
    - cd Epi_SEIR
    - pwd
    - pytest --junitxml=Epi_SEIR/unit_testing/report.xml
    - pwd
  artifacts:
    when: always
    reports:
      junit: Epi_SEIR/unit_testing/report.xml
