default:
  image: python:3.8
  before_script:
    - pip install pytest
      #- apt-get update
      #- apt-get install -y python3-pip
      #- pip install -r requirements.txt
test:
  script:
    cd Epi_SEIR
    pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
#pytest:
#  stage: test
#  script:
#    - pytest --junitxml=Epi_SEIR/unit_testing/report.xml
#  artifacts:
#    when: always
#    reports:
#      junit: Epi_SEIR/unit_testing/report.xml
