DENGUE:
  PARAMETERS:
    psi: 0.9
    nu_h: 2.0e-08
    nu_v: 100000
    gamma_h: 1000000.0
    mu_v: 0.2
    b_h: 2
    b_v: 2
    beta_h: 0.14285714285714285
    beta_v: 0.14285714285714285
    N_h: 100
    N_v: 100
  INITIAL_STATES:
    Sh: 8
    Eh: 0
    Iha: 1
    Ihs: 0
    Rh: 0
    Sv: 0
    Ev: 0
    Iv: 0
WNV:
  t2: 22
  tt: 33
  ttt: 44
