#------------------------------------------#
# Vector Borne Disease Model Configuration #
#------------------------------------------#

PROJECT_ROOT: '.'
LOGFILE_PATH: 'logs'
MOSQUITOES_FILE_PATH: 'mosquitoes/mosq.csv'
INITIAL_STATES_FILE_PATH: 'initial_states_input/unit_testing/working_initial_states.yaml'
OUTPUT_DIR: 'human_model_output'

# Add unit test specification?
OUTPUT_TYPE: '.csv' # default is .parquet

DURATION: 363 # number of days to run the model
RESOLUTION: 1 # how many points to run per day

DENGUE:
  PARAMETERS:
    psi_h: 0.0000391
    nu_h: 0.164 
    nu_v: 0.0667 #25C values
    gamma_h: 0.167 
    mu_v: .0332 #25C values 
    mu_h: 0.0000391
    sigma_h: 19
    sigma_v: 0.5
    beta_h: 0.33
    beta_v: 0.33
    r: 0.0087 #all these values are from Toronto 2014 fits
    K: 328948.585
    r_s: -0.0267
    K_s: 323830.319
    alpha_h: 0.00011 
  FIT: True
  FIT_METHOD: 'nbinom' #can be pois, nbinom, norm
  DISPERSION: 1
  CALC_CI: False
  FIT_PARAMS:
    beta_v:
      min: 0
      max: 1
      proflike: 0.1
    dispersion:
      min: 0.00001
      max: 100
      proflike: .9
  FIT_DATA: 
    PATH: ['fit_data/old/rio_fit_data_2010.csv']
    res: ['weekly']
    compartment: ['Rh']
    
WNV:
  PARAMETERS:
    mu_v: 0.06
    mu_b: 0.004
    gamma_b: 0.2 #guess for now
    alpha_v: 0.69
    alpha_b: 0.74
    beta_b: 0.44
    eta: 0.003
    K: 292870.0294 # from Toronto 20018 season fitting
    K_s: 289323.6226
    r: -0.015161776
    r_s: -0.04379221728
#     K_v: 15000
#     r_v: 0.2286
    rho: 0.0003
    rho_s: 0.001
    theta: 0.01
    nu_v: 0.10
    nu_b: 0.20 #guess for now
  FIT: True
  FIT_METHOD: 'pois' #can be pois, nbinom, normal
  DISPERSION: 0.0001
  CALC_CI: False
  FIT_PARAMS:
    nu_v:
      min: 0.07
      max: .14
    Sv:
      min: 5000
      max: 30000
  FIT_DATA: 
    PATH: ['fit_data/old/Toronto_totmosq_2004.csv']
    res: ['daily']
    compartment: ['Sv']
