#------------------------------------------#
# Vector Borne Disease Model Configuration #
#------------------------------------------#

PROJECT_ROOT: '/Users/jkeithley/Documents/human_epi_models/Epi_SEIR'
LOGFILE_PATH: '/Users/jkeithley/Documents/human_epi_models/Epi_SEIR/logs'
INITIAL_STATES_FILE_PATH: '/Users/jkeithley/Documents/human_epi_models/Epi_SEIR/initial_states_input/initial_states.yaml'
LLM_OUTPUT_DIR: '/Users/jkeithley/Documents/human_epi_models/Epi_SEIR/LLM_output'
OUTPUT_DIR: '/Users/jkeithley/Documents/human_epi_models/Epi_SEIR/human_model_output'

# Add unit test specification?
OUTPUT_TYPE: 'csv' # default is .parquet

DURATION: 363 # number of days to run the model
RESOLUTION: 1

DATES:
  start1: '04-15'
  start2: '05-15'
  end1: '09-01' 
  end2: '11-01' 
  start_year: '2005'
  end_year: '2007'    
POPULATION:
  type: 'Active'  
DATA_COL_NAMES:
  date: 'date'
  total_mosq: 'TotMosq'
  active_mosq: 'mosquito_count'
  
  
DENGUE:
  PARAMETERS:
    #biting_rate: 0.0014
    biting_rate: 'parameters/test_spline.pkl' #DUMMY SPLINE, NOT FOR REAL MODEL
    psi_h: 0.0000391
    nu_h: 0.164 
    nu_v: 0.0667 #25C values 
    gamma_h: 0.167 
    mu_v: .0332 #25C values 
    mu_h: 0.0000391
    sigma_h: 19
    sigma_v: 0.5
    beta_h: 0.33
    beta_v: 0.33
    K: 292870.0294 # from Toronto 2018 season fitting
    K_s: 289323.6226
    r: -0.015161776
    r_s: -0.04379221728
    alpha_h: 0.00011 #just a guess, this means they could be reinfected 25 years later 
  FIT: False
  FIT_METHOD: 'nbinom' #can be pois, nbinom, norm
  DISPERSION: 0.1
  CALC_CI: True
  FIT_PARAMS:
    nu_h:
      min: 0.07
      max: .33
    gamma_h:
      min: 0.08
      max: .25
    Sv:
      min: 10000000
      max: 60000000
  TIMEDEP_FIT_PARAMS:
    biting_rate:
      initial: 0.0014
      min: 0
      max: 100
      num_points: 3
      proflike: 40
#data needs to be in exact formatting to compare to a given compartment
  FIT_DATA: 
    PATH: ['fit_data/old/rio_fit_data_2010.csv']
    res: ['weekly'] #can be weekly or daily, regardless set resolution to 1
    compartment: ['Rh']
    
WNV:
  PARAMETERS:
    mu_v: 0.06
    mu_b: 0.004
    gamma_b: 0.2 #guess for now
    beta_v: 0.69
    beta_b: 0.74
    alpha: 0.44
    eta: 0.003
    K: 292870.0294 # from Toronto 2018 season fitting
    K_s: 289323.6226
    r: -0.015161776
    r_s: -0.04379221728
    rho: 0.003
    rho_s: 0.001
    theta: 0.05
    nu_v: 0.10
    nu_b: 0.20 #guess for now
    m: 0.80 #guess for now
  FIT: False
  FIT_METHOD: 'pois' #can be pois, nbinom, normal
  DISPERSION: 0.0001
  CALC_CI: False
  FIT_PARAMS:
    nu_v:
      min: 0.07
      max: .14
    mu_v:
      min: 0.016
      max: .33
    Sv:
      min: 5000
      max: 30000
#data needs to be in exact formatting to compare to a given compartment
  FIT_DATA: 
    PATH: ['fit_data/old/Toronto_totmosq_2004.csv']
    res: ['daily'] #can be weekly or daily, regardless set resolution to 1
    compartment: ['Sv']
