#------------------------------------------#
# Vector Borne Disease Model Configuration # (add more specific info in this later)
#------------------------------------------#

PROJECT_ROOT: 'HUMAN_EPI_MODEL_PATH'
LOGFILE_PATH: 'LOGS_PATH'
MOSQUITOES_FILE_PATH: 'HUMAN_EPI_MODEL_PATH/mosquitoes'
INITIAL_STATES_FILE_PATH: 'HUMAN_EPI_MODEL_PATH/initial_states_input/initial_states.yaml'
OUTPUT_DIR: 'HUMAN_EPI_MODEL_OUTPUT_PATH'

# Add unit test specification?
OUTPUT_TYPE: 'csv' # default is .parquet

DURATION: 10 # number of days to run the model
RESOLUTION: 50 # how many points to run per day

DENGUE:
  PARAMETERS:
    psi: 0.5
    nu_h: 5
    nu_v: 9
    gamma_h: 7
    mu_v: 12
    beta_h: 0.5
    beta_v: 0.75
    sigma_h: 19
    sigma_v: 0.5
WNV:
  PARAMETERS:
    mu_v: 0.5
    alpha: 5
    delta_b: 9
    eta: 0.1
    A: 1
    K: 5
    r: 1
    t0: 2
