#------------------------------------------#
# Vector Borne Disease Model Configuration #
#------------------------------------------#

PROJECT_ROOT: 'HUMAN_EPI_MODEL_PATH' # (e.g., '/Users/jkeithley/Documents/CIMMID/human/dengue_model/Epi_SEIR')
LOGFILE_PATH: 'HUMAN_EPI_LOGS_PATH' # (e.g., '/Users/jkeithley/Documents/CIMMID/human/dengue_model/Epi_SEIR/logs') 
MOSQUITOES_FILE_PATH: 'HUMAN_EPI_MODEL_PATH/mosquitoes/mosq.csv' # (e.g., '/Users/jkeithley/Documents/CIMMID/human/dengue_model/Epi_SEIR/mosquitoes')
INITIAL_STATES_FILE_PATH: 'HUMAN_EPI_MODEL_PATH/initial_states_input/initial_states.yaml' # (e.g., '/Users/jkeithley/Documents/CIMMID/human/dengue_model/Epi_SEIR/initial_states_input/initial_states.yaml')
OUTPUT_DIR: 'HUMAN_EPI_MODEL_OUTPUT_PATH' # (e.g., '/Users/jkeithley/Documents/CIMMID/human/dengue_model/Epi_SEIR/human_model_output')

# Add unit test specification?
OUTPUT_TYPE: 'csv' # default is .parquet

DURATION: 363 # number of days to run the model
RESOLUTION: 1

DENGUE:
  PARAMETERS:
    nu_h: 0.106
    nu_v: 0.106 
    gamma_h: 0.167
    mu_v: .107 
    beta_h: 0.101
    beta_v: 0.606
    a_v: 0.307
    r_v: .190 
    K_v: 688818
  FIT: False
  FIT_PARAMS:
    nu_h:
      min: 0.07
      max: .33
    gamma_h:
      min: 0.08
      max: .25
    Sv:
      min: 10000000
      max: 60000000
  FIT_DATA: 
    PATH: ['fit_data/old/rio_fit_data_2010.csv']
    res: ['weekly']
    compartment: ['Rh']
    
WNV:
  PARAMETERS:
    mu_v: 0.06
    mu_b: 0.004
    alpha_v: 0.69
    alpha_b: 0.74
    beta_b: 0.44
    eta: 0.003
    K_v: 15000
    r_v: 0.2286
    nu_v: 0.10
    nu_b: 0.20
  FIT: False
  FIT_PARAMS:
    nu_v:
      min: 0.07
      max: .14
    mu_v:
      min: 0.016
      max: .33
    Sv:
      min: 5000
      max: 30000
  FIT_DATA: 
    PATH: ['fit_data/old/Toronto_totmosq_2004.csv']
    res: ['daily'] 
    compartment: ['Sv']
