#------------------------------------------#
# Vector Borne Disease Model Configuration #
#------------------------------------------#

PROJECT_ROOT: '.'
LOGFILE_PATH: 'logs'
MOSQUITOES_FILE_PATH: 'mosquitoes/mosq.csv'
INITIAL_STATES_FILE_PATH: 'initial_states_input/initial_states.yaml'
PARAMETER_FIT_DIR: 'param_fit_output'
OUTPUT_DIR: 'human_model_output'

OUTPUT_TYPE: '.csv' # default is .parquet

DURATION: 398 # number of days to run the model
RESOLUTION: 1

DENGUE:
  PARAMETERS:
    nu_h: 0.164
    nu_v: 0.2 
    gamma_h: 0.17 
    mu_v: .0714 
    beta_h: 0.33
    beta_v: 0.33
    a_v: 0.3
    r_v: .2286
    #r_v: .5
    #K_v: 200000
    K_v: 4028296
  FIT: True
  FIT_METHOD: 'nbinom' #can be res, pois, nbinom, norm
  DISPERSION: 5
  FIT_PARAMS:
    nu_h:
      min: 0.0001
      max: .4
      proflike: 0.001
#     beta_v:
#       min: 0.1
#       max: 0.9
#       proflike: 0.05
    a_v:
      min: 0
      max: 0.8
      proflike: 0.001
#     gamma_h:
#       min: 0.0001
#       max: 0.5
#       proflike: 0.2
#     mu_v:
#       min: 0
#       max: 0.4
#       proflike: 0.05
#     Sv:
#       #min: 1687000
#       min: 0
#       max: 26992000
#       proflike: .03
#     Iv:
#       min: 0
#       max: 10000
#       proflike: .055
#     #Iv:
#       #min: 5
#       #max: 15
#     K_v:
#       min: 0
#       max: 26992000
#       proflike: .01
    
#    K_v: 
#      min: 10
#     max: 1000
#data needs to be in exact formatting to compare to a given compartment
  FIT_DATA: 
    PATH: ['fit_data/sim_data.csv']
    res: ['weekly'] #can be weekly or daily, regardless set resolution to 1
    compartment: ['Dh']
    
WNV:
  PARAMETERS:
    mu_v: 0.06
    mu_b: 0.004
    alpha_v: 0.69
    alpha_b: 0.74
    beta_b: 0.44
    eta: 0.003
    #K: 9596.401 # from Toronto 2004 season fitting
    #K_s: 8946.468
    #r: 0.00438 
    #r_s: 0.00976
    K_v: 15000
    r_v: 0.2286
    nu_v: 0.10
    nu_b: 0.20 #guess for now
  FIT: False
  FIT_METHOD: 'pois' #can be res, pois, nbinom, normal
  FIT_PARAMS:
    nu_v:
      min: 0.07
      max: .14
    mu_v:
      min: 0.016
      max: .33
    Sv:
      min: 5000
      max: 30000
#data needs to be in exact formatting to compare to a given compartment
  FIT_DATA: 
    PATH: ['fit_data/old/Toronto_totmosq_2004.csv']
    res: ['daily'] #can be weekly or daily, regardless set resolution to 1
    compartment: ['Sv']
