#------------------------------------------#
# Sequence Parameter Values Configuration  #
#------------------------------------------#

PROJECT_ROOT: '.'
OUTPUT_DIR: 'parameters'

DENGUE:
  #nu_h:
    #start: 0.07
    #step: 0.03
    #stop: .33
  beta_v:
    start: 0.1
    step: 0.1
    stop: 1
  dispersion:
    start: 0.1
    step: 0.3
    stop: 2
#   Sv:
#     start: 10
#     step: 50
#     stop: 1000
#   K_v:
#     start: 10
#     step: 50
#     stop: 1000

WNV:
  nu_v:
    start: 0.2
    step: 0.1
    stop: 0.5
  mu_v:
    start: 0.04
    step: 0.02
    stop: 0.1
  Sb:
    start: 400
    step: 50
    stop: 600

