#------------------------------------------#
# Vector Borne Disease Model Configuration #
#------------------------------------------#

PROJECT_ROOT: '.'
LOGFILE_PATH: 'logs'
MOSQUITOES_FILE_PATH: 'mosquitoes/mosq.csv'
INITIAL_STATES_FILE_PATH: 'initial_states_input/initial_states.yaml'
OUTPUT_DIR: 'human_model_output'

# Add unit test specification?
OUTPUT_TYPE: '.csv' # default is .parquet

DURATION: 10 # number of days to run the model
RESOLUTION: 50 # how many points to run per day

DENGUE:
  PARAMETERS:
    psi: 0.5
    nu_h: 5
    nu_v: 9
    gamma_h: 7
    mu_v: 12
    beta_h: 0.5
    beta_v: 0.75
    sigma_h: 19
    sigma_v: 0.5
WNV:
  PARAMETERS:
    mu_v: 0.06
    mu_b: 0.20
    alpha_v: 0.69
    alpha_b: 0.74
    beta_b: 0.44
    eta: 0.003
    K_b: 9596.401 # from Toronto 2004 season fitting
    K_s: 8946.468
    r_b: 0.00438 
    r_s: 0.00976
    nu_v: 0.10

