DENGUE:
  PARAMETERS:
    K_v: 100000000
    a_v: 1
    beta_h: 0.33
    beta_v: 0.33
    gamma_h: 0.167
    mu_v: 0.0714
    nu_h: 0.2
    nu_v: 0.1
    r_v: 0.2286
DURATION: 10
INITIAL_STATES_FILE_PATH: initial_states_input/initial_states.yaml
LOGFILE_PATH: logs
MOSQUITOES_FILE_PATH: mosquitoes/mosq.csv
OUTPUT_DIR: human_model_output
OUTPUT_TYPE: .csv
PROJECT_ROOT: .
RESOLUTION: 50
WNV:
  PARAMETERS:
    K_b: 9596.401
    K_s: 8946.468
    alpha_b: 0.74
    alpha_v: 0.69
    beta_b: 0.44
    eta: 0.003
    mu_b: 0.2
    mu_v: 0.0799999999999999
    nu_v: 0.4000000000000001
    r_b: 0.00438
    r_s: 0.00976
