#------------------------------------------#
# Vector Borne Disease Model Configuration #
#------------------------------------------#

PROJECT_ROOT: '.'
LOGFILE_PATH: 'logs'
INITIAL_STATES_FILE_PATH: 'initial_states_input/initial_states.yaml'
LLM_OUTPUT_DIR: 'LLM_output'
OUTPUT_DIR: 'human_model_output'

OUTPUT_TYPE: '.csv' # default is .parquet

DURATION: 363 # number of days to run the model
RESOLUTION: 1


DATES:
  start1: '04-15'
  start2: '05-15'
  end1: '09-01' 
  end2: '11-01' 
  start_year: '2005'
  end_year: '2007'    
POPULATION:
  type: 'Active'  
DATA_COL_NAMES:
  date: 'date'
  total_mosq: 'TotMosq'
  active_mosq: 'mosquito_count'
  
  
DENGUE:
  PARAMETERS:
    nu_h: 0.164 
    nu_v: 0.164 
    gamma_h: 0.167 
    mu_v: .0714 
    beta_h: 0.33
    beta_v: 0.33
    a_v: 0.75
    r_v: .2286
    K_v: 200000
  FIT: False
  FIT_PARAMS:
    nu_h:
      min: 0.07
      max: .33
    gamma_h:
      min: 0.08
      max: .25
    Sv:
      min: 10000000
      max: 60000000
#data needs to be in exact formatting to compare to a given compartment
  FIT_DATA: 
    PATH: ['fit_data/old/rio_fit_data_2010.csv']
    res: ['weekly'] #can be weekly or daily, regardless set resolution to 1
    compartment: ['Rh']
    
WNV:
  PARAMETERS:
    mu_v: 0.06
    mu_b: 0.004
    gamma_b: 0.2 #guess for now
    #alpha_v: 0.69
    #alpha_b: 0.74
    #beta_b: 0.44
    alpha_v: 1
    alpha_b: 1
    beta_b: 1
    eta: 0.003
    K: 292870.0294 # from Toronto 20018 season fitting
    K_s: 289323.6226
    r: -0.015161776
    r_s: -0.04379221728
#     K_v: 15000
#     r_v: 0.2286
    rho: 0.003
    rho_s: 0.001
    theta: 0.05
    nu_v: 0.10
    nu_b: 0.20 #guess for now
  FIT: False
  FIT_PARAMS:
    nu_v:
      min: 0.07
      max: .14
    mu_v:
      min: 0.016
      max: .33
    Sv:
      min: 5000
      max: 30000
#data needs to be in exact formatting to compare to a given compartment
  FIT_DATA: 
    PATH: ['fit_data/old/Toronto_totmosq_2004.csv']
    res: ['daily'] #can be weekly or daily, regardless set resolution to 1
    compartment: ['Sv']
