name: human-epi-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9 
  - numpy
  - pandas
  - scipy
  - pyarrow
  - pyyaml
  - matplotlib
  - sphinx
  - pytest
  - lmfit
  - statsmodels
